<script type="text/javascript">
    var searchSection = 'global';
    var searchCountry = 'us';
</script>
<script src="http://images.apple.com/global/nav/scripts/globalnav.js" type="text/javascript" charset="utf-8"></script>
<nav id="globalheader" class="apple">

<ul id="menu">
    <li><a href="/codemonkeys/index.shtml">Home</a></li>
    <li><a href="/codemonkeys/protosite/index.shtml">Proto-site</a></li>
    <li><a id="current" href="/codemonkeys/wireframe.shtml">WireFrames</a></li>
</ul>

     <div id="globalsearch">

        <form action="http://www.google.com/search" method="get" class="search" id="g-search">
        <div class="sp-label">
            <label for="sp-searchtext">Search</label>
            <input type="text" name="q" id="sp-searchtext" accesskey="s" />
	    <input type="hidden" name="sitesearch" value="teams.thenet.ca/codemonkeys/" />
        </div>
	</form>

        <div id="sp-magnify"><div class="magnify-searchmode"></div><div class="magnify"></div></div>
        <div id="sp-results"></div>
    </div>
</nav>
