<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link type="text/css" rel="stylesheet" href="/codemonkeys/protosite/normalize.css" /> <!-- CSS Reset -->
<link href='http://fonts.googleapis.com/css?family=Scada' rel='stylesheet' type='text/css'>
<link id="globalheader-stylesheet" rel="stylesheet" href="http://images.apple.com/global/nav/styles/navigation.css" type="text/css" />
<link type="text/css" rel="stylesheet" href="/codemonkeys/protosite/style.css" title="Normal Style" /> <!-- Default Style -->
<link type="text/css" rel="alternate stylesheet" href="/codemonkeys/protosite/overhead.css" title="Overhead Style" /> <!-- Alternate -->
<link type="text/css" rel="stylesheet" href="/codemonkeys/protosite/mobile.css" media="only screen and (max-device-width:600px)" /> <!-- Mobile CSS -->
<meta name="viewport" content="width=device-width, initial-scale=1" /> <!-- Needed for phones -->
<script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
