<nav id="bottom_nav">
        <a href="#top">Top of Page</a> 
        <span class="none"> | </span>

        <a href="http://my.bcit.ca/">my.bcit</a>
        <span class="none"> | </span>

        <a href="http://www.bcit.ca/">bcit</a>
        <span class="none"> | </span>

        <a href="http://www.computing.bcit.ca/">bcit: computing</a>
        <span class="none"> | </span>

        <a href="http://www.alistair.com/">alistair.com</a>
        
</nav>

<footer>
        <p id="referer">
                <a href="http://validator.w3.org/check?uri=referer"><img src="images/HTML5_1Color_Black.png" alt="HTML 5 logo"/></a>
        </p>
        <p id="copyright">Copyright&copy;Code Monkey 2012</p>
</footer>
