<script type="text/javascript">
    var searchSection = 'global';
    var searchCountry = 'us';
</script>
<link id="globalheader-stylesheet" rel="stylesheet" href="http://images.apple.com/global/nav/styles/navigation.css" type="text/css" />
<script src="http://images.apple.com/global/nav/scripts/globalnav.js" type="text/javascript" charset="utf-8"></script>
<nav id="globalheader" class="apple">
<ul id="menu">
	<li><a href="/codemonkeys/protosite/index.shtml">Home</a></li>
	<li><a href="/codemonkeys/protosite/course_outline.shtml">Course Outline</a></li>
	<li>
		<a href="#">Lecture</a>
		<ul>
			<li><a href="/codemonkeys/protosite/lectures/lecture1.shtml">Week 1</a></li>
			<li><a href="#">Week 2</a></li>
			<li><a href="#">Week 3</a></li>
			<li><a href="#">Week 4</a></li>
			<li><a href="#">Week 5</a></li>
			<li><a href="#">Week 6</a></li>
			<li><a href="#">Week 7</a></li>
			<li><a href="#">Week 8</a></li>
			<li><a href="#">Week 9</a></li>
			<li><a href="#">Week 10</a></li>
			<li><a href="#">Week 11</a></li>
			<li><a href="#">Week 12</a></li>
		</ul>
	</li>
	<li><a href="http://codemonkeys1950project.tumblr.com/">Blog</a></li>
	<li><a ${contact} href="/codemonkeys/protosite/contact.shtml">Contact</a></li>
	<li><a href="/codemonkeys/protosite/sitemap.shtml">Site Map</a></li>
</ul>

     <div id="globalsearch">

        <form action="http://www.google.com/search" method="get" class="search" id="g-search"><div class="sp-label">
            <label for="sp-searchtext">Search</label>
            <input type="text" name="q" id="sp-searchtext" accesskey="s" />
	    <input type="hidden" name="sitesearch" value="teams.thenet.ca/codemonkeys" />
        </div></form>
        <div id="sp-magnify"><div class="magnify-searchmode"></div><div class="magnify"></div></div>
        <div id="sp-results"></div>
    </div>
</nav>
