
	<li><a href="/codemonkeys/protosite/index.shtml">Home</a></li>
	<li><a href="/codemonkeys/protosite/course_outline.shtml">Course Outline</a></li>
	<li>
		<a href="#">Lecture <span class="arrow-down"></span></a>
		<ul>
			<li><a href="/codemonkeys/protosite/lectures/lecture1.shtml">Week 1</a></li>
			<li><a href="#">Week 2</a></li>
			<li><a href="#">Week 3</a></li>
			<li><a href="#">Week 4</a></li>
			<li><a href="#">Week 5</a></li>
			<li><a href="#">Week 6</a></li>
			<li><a href="#">Week 7</a></li>
			<li><a href="#">Week 8</a></li>
			<li><a href="#">Week 9</a></li>
			<li><a href="#">Week 10</a></li>
			<li><a href="#">Week 11</a></li>
			<li><a href="#">Week 12</a></li>
		</ul>
	</li>
	<li><a id="current" href="http://codemonkeys1950project.tumblr.com/">Blog</a></li>
	<li><a href="/codemonkeys/protosite/contact.shtml">Contact</a></li>
	<li><a href="/codemonkeys/protosite/sitemap.shtml">Site Map</a></li>
