</ul>

     <div id="globalsearch">

        <form action="http://www.google.com/search" method="get" class="search" id="g-search"><div class="sp-label">
            <label for="sp-searchtext">Search</label>
            <input type="text" name="q" id="sp-searchtext" accesskey="s" />
	    <input type="hidden" name="sitesearch" value="teams.thenet.ca/codemonkeys/" />
        </div></form>
        <div id="sp-magnify"><div class="magnify-searchmode"></div><div class="magnify"></div></div>
        <div id="sp-results"></div>
    </div>
</nav>
